copr: be: install new mock on builders
This allowed me to remove many hacks, but mostly this is needed to make
fedora-rawhide builds work again, per build errors:

    GPG Keys are configured as:
    file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-32-primary,
    file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-32-primary,
    file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-31-primary
    Error: GPG check FAILED

Unfortunately, due to preparations for temporary movement to AWS cloud
we don't have a working stating instance... so trying directly against
production.